### ISSUE TITLE
IdP v3 version?

### ISSUE THREAD

**Issue by illtud** [ukf/ua-attribute-idp-ext#5]
Hi, don't know if this is still used out there, but are there any plans to develop an IdP v3 version of this useful extension?

**Comment by iay** [comment]
The v3 IdP is a lot more capable, and everything you need to implement this kind of functionality is there if you can write a script. We therefore have no plans to make a v3 version of this extension.

**Comment by iay** [comment]
It may be worth asking in the Shibboleth users list to see if someone has scripted something similar already.
